# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

name: pull_request_target

on: pull_request_target

permissions:
  contents: read
  pull-requests: read

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/pull-request-target.yml@d4fbab18738500fb2cdf8e23ab3fb79374fcb375 # master
    secrets: inherit
